services:
  app:
    build: .
    command: npm run dev
    ports:
      - "9000:9000"

    volumes:
      - .:/app
  db:
    image: postgres
    container_name: tickydb
    restart:
      always
      # set shared memory limit when using docker-compose
    # shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    networks:
      - db-host
    ports:
      - "9001:5432"

    environment:
      POSTGRES_DB: tickydb
      POSTGRES_USER: nycol
      POSTGRES_PASSWORD: passW123

    volumes:
      - ~/.PostgreSQLData/tickydb:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    networks:
      - db-host
    ports:
      - "9002:80"

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@tickyapp.com
      PGADMIN_DEFAULT_PASSWORD: pass@admin

    # volumes:
    #   - ~/.pgAdmin/data:/var/lib/pgadmin

networks:
  db-host:
    driver: bridge
